# Generated by Django 5.2.6 on 2025-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentity',
            name='audit_evidence',
            field=models.TextField(blank=True, help_text="The raw, verifiable proof that supports the audit's findings. Examples: System log files, signed contracts, screenshots of firewall configurations, interview notes, or financial statements."),
        ),
        migrations.AddField(
            model_name='auditentity',
            name='audit_findings',
            field=models.TextField(blank=True, help_text="The detailed analysis that compares the evidence to the criteria. Examples: 'The organization lacks a formal policy for password complexity, which is a violation of NIST CSF control AC-1.'"),
        ),
        migrations.AddField(
            model_name='auditentity',
            name='audit_scope_criteria',
            field=models.TextField(blank=True, help_text='Defines the boundaries of the audit and the specific rules or standards it is being measured against. Examples: Scope: Financial transactions for Q3 2024. Criteria: GAAP or SOX.'),
        ),
        migrations.AddField(
            model_name='auditentity',
            name='auditor_opinion_conclusion',
            field=models.TextField(blank=True, help_text="The final, formal verdict or summary statement based on all the collected evidence and findings. Examples: 'The company is in full compliance with ISO 27001' or 'We found material weaknesses in the internal controls.'"),
        ),
    ]
