# Generated by Django 5.2.6 on 2025-09-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_auditentity_audit_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentity',
            name='audit_frequency',
            field=models.CharField(blank=True, choices=[('Annual', 'Annual'), ('Biennial', 'Biennial'), ('Triennial', 'Triennial'), ('Ad Hoc', 'Ad Hoc'), ('Continuous', 'Continuous'), ('As Needed', 'As Needed')], default='Annual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditentity',
            name='criticality',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10, null=True),
        ),
    ]
