# Generated by Django 5.2.6 on 2025-09-15 20:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_document_auditentity_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='auditentity',
            name='attachments',
        ),
        migrations.RemoveIndex(
            model_name='auditentity',
            name='audits_audi_technic_babfe4_idx',
        ),
        migrations.RemoveField(
            model_name='auditentity',
            name='technical_owner',
        ),
        migrations.AddField(
            model_name='auditentity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_audit_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditentity',
            name='audit_frequency',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Biennial', 'Biennial'), ('Ad Hoc', 'Ad Hoc')], default='Annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditentity',
            name='business_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_owned_audit_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditentity',
            name='control_maturity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='auditentity',
            name='criticality',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditentity',
            name='inherent_risk_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='auditentity',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditentity',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditentity',
            name='residual_risk_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='auditentity',
            name='risk_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddIndex(
            model_name='auditentity',
            index=models.Index(fields=['owner'], name='audits_audi_owner_i_f861b0_idx'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
