# Generated by Django 5.2.6 on 2025-09-16 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0011_update_audit_frequency_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("planned_start", models.DateField()),
                ("planned_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("objectives", models.TextField(blank=True)),
                ("scope", models.TextField(blank=True)),
                ("resources", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_plans",
                        to="audits.auditentity",
                    ),
                ),
                (
                    "lead_auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_audit_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Plan",
                "verbose_name_plural": "Audit Plans",
                "ordering": ["planned_start"],
                "indexes": [
                    models.Index(
                        fields=["entity"], name="audits_audi_entity__521d9f_idx"
                    ),
                    models.Index(
                        fields=["lead_auditor"], name="audits_audi_lead_au_0ea4b5_idx"
                    ),
                    models.Index(
                        fields=["status"], name="audits_audi_status_985ae8_idx"
                    ),
                    models.Index(
                        fields=["planned_start"], name="audits_audi_planned_b6eb1e_idx"
                    ),
                    models.Index(
                        fields=["planned_end"], name="audits_audi_planned_7efb77_idx"
                    ),
                ],
            },
        ),
    ]
