# Generated by Django 5.2.6 on 2025-09-16 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0012_add_audit_plan_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPlanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Plan Approval',
                'verbose_name_plural': 'Audit Plan Approvals',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_audit_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_audit_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='requires_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_audit_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='submitted_for_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['submitted_for_approval_at'], name='audits_audi_submitt_bb453e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['approved_at'], name='audits_audi_approve_c0fbce_idx'),
        ),
        migrations.AddField(
            model_name='auditplanapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_plan_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditplanapproval',
            name='audit_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='audits.auditplan'),
        ),
        migrations.AddIndex(
            model_name='auditplanapproval',
            index=models.Index(fields=['audit_plan'], name='audits_audi_audit_p_f4a982_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplanapproval',
            index=models.Index(fields=['approver'], name='audits_audi_approve_747480_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplanapproval',
            index=models.Index(fields=['status'], name='audits_audi_status_f0343e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditplanapproval',
            index=models.Index(fields=['created_at'], name='audits_audi_created_075fcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditplanapproval',
            unique_together={('audit_plan', 'approver')},
        ),
    ]
