# Generated by Django 5.2.6 on 2025-09-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0016_add_geographical_location_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditentity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("business_unit", "Business Unit"),
                    ("division", "Division"),
                    ("function", "Function"),
                    ("section", "Section"),
                    ("unit", "Unit"),
                    ("process", "Process"),
                    ("system", "System"),
                    ("vendor", "Vendor"),
                    ("compliance_domain", "Compliance Domain"),
                ],
                max_length=50,
            ),
        ),
    ]
