# Generated by Django 5.2.6 on 2025-09-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0019_add_key_contact_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditentity",
            name="objectives",
            field=models.TextField(
                blank=True,
                help_text="Key responsibilities and goals of this entity",
                null=True,
            ),
        ),
    ]
