# Generated by Django 5.2.6 on 2025-09-29 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0023_add_process_depends_on"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditentity",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users assigned as owners of this entity",
                related_name="assigned_entities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
