# Generated by Django 5.2.6 on 2025-10-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0026_add_audit_plan_enhancements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("in_review", "In Review"),
                    ("rejected", "Rejected"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
