# Generated by Django 5.2.6 on 2025-10-14 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0029_rename_audits_audi_audit_t_idx_audits_audi_audit_t_3c19be_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentity',
            name='team_member',
            field=models.ForeignKey(blank=True, help_text='Entity team member/assigned person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_audit_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditentity',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Entity owner/lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_audit_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditentity',
            index=models.Index(fields=['team_member'], name='audits_audi_team_me_f69db9_idx'),
        ),
    ]
