# Generated by Django 5.2.6 on 2025-10-16 14:27

import django.db.models.deletion
import iam.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audits", "0032_add_checklist_execution"),
        ("iam", "0014_user_observation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="checklist",
            new_name="audits_chec_folder__f55dbd_idx",
            old_name="audits_chec_folder__f5c21e_idx",
        ),
        migrations.RenameIndex(
            model_name="checklist",
            new_name="audits_chec_status_81c3d9_idx",
            old_name="audits_chec_status_6a8e12_idx",
        ),
        migrations.RenameIndex(
            model_name="checklist",
            new_name="audits_chec_created_ab40ef_idx",
            old_name="audits_chec_created_3b9f45_idx",
        ),
        migrations.RenameIndex(
            model_name="checklist",
            new_name="audits_chec_created_bc4356_idx",
            old_name="audits_chec_created_b8c534_idx",
        ),
        migrations.RenameIndex(
            model_name="checklist",
            new_name="audits_chec_is_publ_5ffa19_idx",
            old_name="audits_chec_is_publ_7d2a91_idx",
        ),
        migrations.RenameIndex(
            model_name="checklistexecution",
            new_name="audits_chec_audit_e_75fc2d_idx",
            old_name="audits_chec_audit_e_idx123",
        ),
        migrations.RenameIndex(
            model_name="checklistexecution",
            new_name="audits_chec_status_bb2fe0_idx",
            old_name="audits_chec_status_idx456",
        ),
        migrations.RenameIndex(
            model_name="checklistexecution",
            new_name="audits_chec_started_2f0ea7_idx",
            old_name="audits_chec_started_idx789",
        ),
        migrations.RenameIndex(
            model_name="checklistitem",
            new_name="audits_chec_checkli_980f0c_idx",
            old_name="audits_chec_checkli_4f8e2a_idx",
        ),
        migrations.RenameIndex(
            model_name="checklistitem",
            new_name="audits_chec_control_558168_idx",
            old_name="audits_chec_control_9e3b1c_idx",
        ),
        migrations.RenameIndex(
            model_name="checklistitem",
            new_name="audits_chec_risk_id_c0b6f4_idx",
            old_name="audits_chec_risk_id_5c7d9f_idx",
        ),
        migrations.RenameIndex(
            model_name="checklistitem",
            new_name="audits_chec_policy__7a4e64_idx",
            old_name="audits_chec_policy__2a4e6b_idx",
        ),
        migrations.RenameIndex(
            model_name="checklistitemresult",
            new_name="audits_chec_executi_c2f318_idx",
            old_name="audits_chec_executi_idx012",
        ),
        migrations.RenameIndex(
            model_name="checklistitemresult",
            new_name="audits_chec_result_51c7dd_idx",
            old_name="audits_chec_result_idx345",
        ),
        migrations.RenameIndex(
            model_name="checklistitemresult",
            new_name="audits_chec_tested__257623_idx",
            old_name="audits_chec_tested__idx678",
        ),
        migrations.AlterField(
            model_name="checklist",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="folder",
            field=models.ForeignKey(
                default=iam.models.Folder.get_root_folder_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_folder",
                to="iam.folder",
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="checklist",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
    ]
