# Generated by Django 5.2.6 on 2025-09-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0096_appliedcontrol_cost_to_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="acquisition_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the asset was acquired",
                null=True,
                verbose_name="Acquisition Date",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("cloud", "Cloud"),
                    ("digital", "Digital"),
                ],
                help_text="ITAM classification of the asset",
                max_length=20,
                null=True,
                verbose_name="Asset Type",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="assigned_user",
            field=models.CharField(
                blank=True,
                help_text="User currently assigned to this asset",
                max_length=200,
                null=True,
                verbose_name="Assigned User",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="audit_logs",
            field=models.JSONField(
                blank=True,
                help_text="Audit trail and change logs",
                null=True,
                verbose_name="Audit Logs",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="compliance_standards",
            field=models.JSONField(
                blank=True,
                help_text="Applicable compliance standards and requirements",
                null=True,
                verbose_name="Compliance Standards",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="compliance_status",
            field=models.CharField(
                blank=True,
                help_text="Current compliance status and certifications",
                max_length=200,
                null=True,
                verbose_name="Compliance Status",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Department or organizational unit",
                max_length=200,
                null=True,
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="deployment_details",
            field=models.TextField(
                blank=True,
                help_text="Details about asset deployment and configuration",
                null=True,
                verbose_name="Deployment Details",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="depreciation_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Current depreciated value of the asset",
                max_digits=12,
                null=True,
                verbose_name="Depreciation Value",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="end_of_life_date",
            field=models.DateField(
                blank=True,
                help_text="Expected end of life or retirement date",
                null=True,
                verbose_name="End of Life Date",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="incident_records",
            field=models.JSONField(
                blank=True,
                help_text="Records of security incidents and responses",
                null=True,
                verbose_name="Incident Records",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="known_vulnerabilities",
            field=models.JSONField(
                blank=True,
                help_text="Known security vulnerabilities and patches",
                null=True,
                verbose_name="Known Vulnerabilities",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="license_expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the license expires",
                null=True,
                verbose_name="License Expiry Date",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="license_key",
            field=models.TextField(
                blank=True,
                help_text="Software license key or activation code",
                null=True,
                verbose_name="License Key",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="Official license number or identifier",
                max_length=200,
                null=True,
                verbose_name="License Number",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="license_type",
            field=models.CharField(
                blank=True,
                help_text="Type of license (perpetual, subscription, etc.)",
                max_length=100,
                null=True,
                verbose_name="License Type",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="maintenance_schedule",
            field=models.TextField(
                blank=True,
                help_text="Scheduled maintenance activities and timeline",
                null=True,
                verbose_name="Maintenance Schedule",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="physical_location",
            field=models.CharField(
                blank=True,
                help_text="Physical location of the asset",
                max_length=200,
                null=True,
                verbose_name="Physical Location",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="preventive_maintenance",
            field=models.TextField(
                blank=True,
                help_text="Preventive maintenance schedule and procedures",
                null=True,
                verbose_name="Preventive Maintenance",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="purchase_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original purchase cost of the asset",
                max_digits=12,
                null=True,
                verbose_name="Purchase Cost",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="security_config",
            field=models.JSONField(
                blank=True,
                help_text="Security configuration settings and policies",
                null=True,
                verbose_name="Security Configuration",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Unique serial number of the asset",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Serial Number",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="service_history",
            field=models.JSONField(
                blank=True,
                help_text="History of service requests and maintenance",
                null=True,
                verbose_name="Service History",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="sla_details",
            field=models.TextField(
                blank=True,
                help_text="Service Level Agreement details and requirements",
                null=True,
                verbose_name="SLA Details",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="spare_parts",
            field=models.TextField(
                blank=True,
                help_text="Available spare parts and inventory",
                null=True,
                verbose_name="Spare Parts",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="specifications",
            field=models.TextField(
                blank=True,
                help_text="Technical specifications and details",
                null=True,
                verbose_name="Specifications",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="total_cost_of_ownership",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total cost of ownership including all expenses",
                max_digits=12,
                null=True,
                verbose_name="Total Cost of Ownership",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="upgrade_history",
            field=models.JSONField(
                blank=True,
                help_text="History of upgrades and version changes",
                null=True,
                verbose_name="Upgrade History",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="vendor",
            field=models.CharField(
                blank=True,
                help_text="Vendor or supplier of the asset",
                max_length=200,
                null=True,
                verbose_name="Vendor",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="virtual_location",
            field=models.CharField(
                blank=True,
                help_text="Virtual or cloud location of the asset",
                max_length=200,
                null=True,
                verbose_name="Virtual Location",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="warranty",
            field=models.TextField(
                blank=True,
                help_text="Warranty information and terms",
                null=True,
                verbose_name="Warranty",
            ),
        ),
    ]
